---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    adminPassword: admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: tempo
            type: tempo
            uid: tempo
            access: proxy
            url: "http://tempo.tempo:3100"
            jsonData:
              httpMethod: GET
          - name: elasticsearch
            type: elasticsearch
            uid: elasticsearch
            access: proxy
            url: "https://elasticsearch-master.elasticsearch:9200"
            basicAuth: true
            basicAuthUser: "elastic"
            jsonData:
              tlsAuth: true
              tlsSkipVerify: true
              tlsAuthWithCACert: false
              esVersion: "8.0+"
              timeField: "@timestamp"
              logMessageField: "log"
              logLevelField: "level"
              maxConcurrentShardRequests: "5"
            secureJsonData:
              basicAuthPassword: "elastic"
          - name: prometheus
            type: prometheus
            uid: prometheus
            access: proxy
            url: "http://kube-prometheus-stack-prometheus.monitoring:9090"
            jsonData:
              exemplarTraceIdDestinations:
                - datasourceUid: tempo
                  name: traceID
          - name: loki
            type: loki
            uid: loki
            access: proxy
            url: "http://loki-gateway.loki:80"
            basicAuth: true
            basicAuthUser: "loki"
            jsonData:
              maxLines: 1000
              httpHeaderName1: "X-Scope-OrgID"
              derivedFields:
                - datasourceUid: tempo
                  matcherRegex: "traceID=(\\w+)"
                  name: TraceID
                  # url will be interpreted as query for the datasource
                  url: '$${__value.raw}'
                - matcherRegex: "traceID=(\\w+)"
                  name: TraceID
                  url: 'http://localhost:16686/trace/$${__value.raw}'
            secureJsonData:
              basicAuthPassword: "loki"
              httpHeaderValue1: "grafana"
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/standard
    dashboards:
      default:
        go-dashboard:
          gnetId: 13240
          revision: 2
          datasource: prometheus
        grpc-dashboard:
          gnetId: 14765
          revision: 3
          datasource: prometheus
        node-exporter-dashboard:
          gnetId: 1860
          revision: 31
          datasource: prometheus
        loki-logs-dashboard:
          gnetId: 13639
          revision: 2
          datasource: loki
    service:
      type: NodePort
    persistence:
      enabled: true
