---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    alertmanager:
      enabled: false
    defaultRules:
      create: false
    grafana:
      enabled: false
    kubernetesServiceMonitors:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kube-state-metrics:
      prometheus:
        monitor:
          enabled: false
    nodeExporter:
      enabled: true
      extraArgs:
        - --collector.cgroups
    prometheus-node-exporter:
      prometheus:
        monitor:
          enabled: false
    prometheusOperator:
      enabled: true
    prometheus:
      enabled: true
      prometheusSpec:
        enableFeatures:
          - exemplar-storage
        evaluationInterval: 10s
        exemplars:
          maxSize: 100000
        podMonitorSelectorNilUsesHelmValues: false
        replicas: 1
        ruleSelectorNilUsesHelmValues: false
        scrapeInterval: 30s
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: standard
              resources:
                requests:
                  storage: 8Gi
