---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      size: "8Gi"
    tempo:
      securityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: False
        seccompProfile:
          type: RuntimeDefault
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 3Gi
    tempoQuery:
      securityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: False
        seccompProfile:
          type: RuntimeDefault
    securityContext:
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
      runAsNonRoot: true
