---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  releaseName: sonarqube
  chart:
    spec:
      chart: sonarqube
      version: '8.0.1'
      sourceRef:
        kind: HelmRepository
        name: sonarqube
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    account:
      currentAdminPassword: admin
      adminPassword: hi
    persistence:
      enabled: true
    plugins:
      install:
        - "https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-2.1.1/sonar-cxx-plugin-2.1.1.488.jar"
    service:
      type: NodePort
