---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: fluent
spec:
  values:
    config:
      outputs: |
        [OUTPUT]
            Name es
            Match kube.*
            Host elasticsearch-master.elasticsearch
            Logstash_Format On
            Retry_Limit False
            tls On
            tls.verify Off
            HTTP_User elastic
            HTTP_Passwd elastic
            Suppress_Type_Name On
