---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/elasticsearch
  - ../base/fluentbit
  - ../base/harbor
  - ../base/kube-prometheus-stack
  - ../base/tempo
  - ../base/grafana
  - ../base/sonarqube
patches:
  - path: elasticsearch-values.yaml
    target:
      kind: HelmRelease
      name: elasticsearch
  - path: fluentbit-values.yaml
    target:
      kind: HelmRelease
      name: fluent-bit
