---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/elasticsearch
  - ../base/fluentbit
  - ../base/grafana
  - ../base/kube-prometheus-stack
  - ../base/sonarqube
  - ../base/tempo
patches:
  - path: elasticsearch-values.yaml
    target:
      kind: HelmRelease
